"""Add reactions fields to comments

Revision ID: e9cd2115a5f9
Revises: c4d9c6744cf6
Create Date: 2024-12-30 14:36:47.855347+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e9cd2115a5f9"
down_revision: Union[str, None] = "c4d9c6744cf6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment_reactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("comment_id", sa.Integer(), nullable=False),
        sa.Column("reaction_type", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("comment_id", "user_id", name="unique_comment_user_reaction"),
    )
    op.create_index(op.f("ix_comment_reactions_comment_id"), "comment_reactions", ["comment_id"], unique=False)
    op.drop_column("comments", "likes")
    op.drop_column("comments", "dislikes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("dislikes", sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column("comments", sa.Column("likes", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f("ix_comment_reactions_comment_id"), table_name="comment_reactions")
    op.drop_table("comment_reactions")
