"""Add user_id to categoryModel

Revision ID: c4d9c6744cf6
Revises: 14a6913427af
Create Date: 2024-12-30 02:52:10.848623+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4d9c6744cf6'
down_revision: Union[str, None] = '14a6913427af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'user_id')
    # ### end Alembic commands ###
