"""add time stamp

Revision ID: 14a6913427af
Revises: 4f40c17900e6
Create Date: 2024-12-29 23:24:06.114930+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "14a6913427af"
down_revision: Union[str, None] = "4f40c17900e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.add_column("categories", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_categories_created_at"), "categories", ["created_at"], unique=False)
    op.add_column("comments", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("posts", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "deleted_at")
    op.drop_column("comments", "deleted_at")
    op.drop_index(op.f("ix_categories_created_at"), table_name="categories")
    op.drop_column("categories", "deleted_at")
    op.drop_column("categories", "created_at")
